name: "mlops_bm"
dependencies:
  - pandas
  - scikit-learn
  - numpy
  - fastapi
  - black
  - ruff
  - mypy
  - loguru
  - skl2onnx
  - onnxruntime
  - fastapi
  - uvicorn
  - requests
  - aiohttp
  - pip:
    - -e .